openapi: 3.0.0
info:
  title: Aloft API V1 Accounts VideoStreaming API
  contact:
    email: support@aloft.ai
  version: 1.0.0
  description: Accounts
tags:
- name: VideoStreaming
  description: VideoStreaming
paths:
  /v1/account/{account_id}/video-streaming:
    get:
      tags:
      - VideoStreaming
      summary: Returns list of open video streaming rooms.
      description: Returns list of open video streaming rooms.
      operationId: e59c33b6a9cadb993d3a961c1db712c1
      parameters:
      - name: account_id
        in: path
        required: true
        schema:
          $ref: '#components/schemas/model_id'
      responses:
        '200':
          description: Successful operation
          content:
            application/json: {}
      security:
      - Aloft Token: []
  /v1/video-streaming:
    get:
      tags:
      - VideoStreaming
      summary: Returns list of in progress video streaming rooms.
      description: Returns list of in progress video streaming rooms.
      operationId: 9a7324a4277cfce455d01d3a7b8b2d66
      parameters:
      - name: token
        in: query
        description: Stream access token
        schema:
          type: string
      - name: id
        in: query
        description: Stream access token id
        schema:
          type: number
      responses:
        '200':
          description: Successful operation
          content:
            application/json: {}
        '403':
          description: Forbidden
  /v1/account/{account_id}/video-streaming/create-room:
    post:
      tags:
      - VideoStreaming
      summary: Creates a new streaming room.
      description: Creates a new streaming room.
      operationId: 7dc5f87559a5b53b632a90880307159f
      parameters:
      - name: account_id
        in: path
        required: true
        schema:
          $ref: '#components/schemas/model_id'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#components/schemas/video_streaming_room_create_request'
      responses:
        '403':
          description: Access Denied
        '401':
          description: Unauthorized
        '422':
          description: Unprocessable Content
        '200':
          description: Successful operation
      security:
      - Aloft Token: []
  /v1/account/{account_id}/video-streaming/access-room:
    post:
      tags:
      - VideoStreaming
      summary: Retrieve access credentials for a stream.
      description: Retrieve access credentials for a stream.
      operationId: 2d2ce1d6c5b075c76c315bb6eea32e85
      parameters:
      - name: account_id
        in: path
        required: true
        schema:
          $ref: '#components/schemas/model_id'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#components/schemas/video_streaming_room_access_request'
      responses:
        '403':
          description: Access Denied
        '401':
          description: Unauthorized
        '422':
          description: Unprocessable Content
        '200':
          description: Successful operation
      security:
      - Aloft Token: []
  /v1/video-streaming/access-room:
    post:
      tags:
      - VideoStreaming
      summary: Retrieve access credentials for a stream.
      description: Retrieve access credentials for a stream.
      operationId: 70f8a129097e32f6aa802311b3ad9aed
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#components/schemas/video_streaming_room_anonymous_access_request'
      responses:
        '403':
          description: Access Denied
        '401':
          description: Unauthorized
        '422':
          description: Unprocessable Content
        '200':
          description: Successful operation
  /v1/account/{account_id}/video-streaming/complete-room:
    post:
      tags:
      - VideoStreaming
      summary: Completes and ends stream.
      description: Completes and ends stream.
      operationId: cfae27e6fa6231c04730e3e94f35c8ef
      parameters:
      - name: account_id
        in: path
        required: true
        schema:
          $ref: '#components/schemas/model_id'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#components/schemas/video_streaming_room_complete_request'
      responses:
        '403':
          description: Access Denied
        '401':
          description: Unauthorized
        '422':
          description: Unprocessable Content
        '200':
          description: Successful operation
      security:
      - Aloft Token: []
  /v1/account/{account_id}/video-streaming/create-link:
    post:
      tags:
      - VideoStreaming
      summary: Create a sharable link for this account's streams.
      description: Create a sharable link for this account's streams.
      operationId: bd127bcf771760b39171e134d6486367
      parameters:
      - name: account_id
        in: path
        required: true
        schema:
          $ref: '#components/schemas/model_id'
      responses:
        '403':
          description: Access Denied
        '401':
          description: Unauthorized
        '422':
          description: Unprocessable Content
        '200':
          description: Successful operation
      security:
      - Aloft Token: []
components:
  securitySchemes:
    Aloft Token:
      type: http
      name: Aloft Token
      in: header
      scheme: bearer
